# Generated by Django 4.2.19 on 2025-02-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_gallery_choice_text_usefuleinfo_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionswater',
            name='data',
        ),
    ]
