# Generated by Django 4.2.19 on 2025-02-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_submissionswater_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
