# Generated by Django 4.2.19 on 2025-02-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='SubmissionsWater',
        ),
    ]
