# Generated by Django 4.2.19 on 2025-02-26 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_access_delete_submissionswater'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Улица', max_length=20)),
                ('house_number', models.IntegerField(help_text='Номер дома', validators=[django.core.validators.MinValueValidator(0)])),
                ('district', models.IntegerField(choices=[(1, 'Участки первой очереди'), (2, 'Участки второй очереди'), (3, 'Участки третьей очереди')], help_text='Очередь участка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['district', 'street', 'house_number'],
                'unique_together': {('street', 'house_number')},
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Номер счетчика ОКОС', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(verbose_name='Дата добавления счетчика')),
                ('land_plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.landplot')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WaterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Показания счетчика', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(verbose_name='Дата подачи показаний')),
                ('water_meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.watermeter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
